services:
  - type: web
    name: amowallet-backend
    runtime: node
    rootDir: crypto-wallet-app/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
