const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');

/**
 * SSL/HTTPS Configuration Manager
 * Handles both development (self-signed) and production (Let's Encrypt) certificates
 */
class SSLConfigManager {
  constructor() {
    this.environment = process.env.NODE_ENV || 'development';
    this.domain = process.env.DOMAIN || 'localhost';
    this.enableHTTPS = process.env.ENABLE_HTTPS === 'true';
  }

  /**
   * Get SSL credentials
   * In production: Use Let's Encrypt certificates
   * In development: Use self-signed certificates
   */
  getSSLCredentials() {
    if (this.environment === 'production') {
      return this.getProductionCredentials();
    } else {
      return this.getDevelopmentCredentials();
    }
  }

  /**
   * Get production SSL credentials (Let's Encrypt)
   */
  getProductionCredentials() {
    const certPath = process.env.SSL_CERT_PATH || '/etc/letsencrypt/live';
    const domainPath = path.join(certPath, this.domain);

    try {
      return {
        key: fs.readFileSync(path.join(domainPath, 'privkey.pem'), 'utf8'),
        cert: fs.readFileSync(path.join(domainPath, 'cert.pem'), 'utf8'),
        ca: fs.readFileSync(path.join(domainPath, 'chain.pem'), 'utf8'),
      };
    } catch (error) {
      console.error('❌ Error loading production SSL certificates:', error.message);
      console.error('📝 Make sure Let\'s Encrypt certificates are installed at:', domainPath);
      console.error('💡 Run: sudo certbot certonly --standalone -d', this.domain);
      throw new Error('Production SSL certificates not found');
    }
  }

  /**
   * Get development SSL credentials (self-signed)
   */
  getDevelopmentCredentials() {
    // First try PFX certificate (generated by PowerShell)
    const pfxPath = process.env.SSL_PFX_PATH || path.join(__dirname, '../../certs/server.pfx');
    const pfxPassword = process.env.SSL_PFX_PASSWORD || 'crypto123';
    
    if (fs.existsSync(pfxPath)) {
      console.log('🔐 Using PFX certificate:', pfxPath);
      return {
        pfx: fs.readFileSync(pfxPath),
        passphrase: pfxPassword
      };
    }

    // Fallback to PEM certificates
    const certDir = path.join(__dirname, '../certs');
    
    // Create certs directory if it doesn't exist
    if (!fs.existsSync(certDir)) {
      fs.mkdirSync(certDir, { recursive: true });
    }

    const keyPath = path.join(certDir, 'key.pem');
    const certPath = path.join(certDir, 'cert.pem');

    // Check if development certificates exist
    if (!fs.existsSync(keyPath) || !fs.existsSync(certPath)) {
      console.log('🔧 Generating self-signed certificates for development...');
      this.generateSelfSignedCert(certDir);
    }

    try {
      return {
        key: fs.readFileSync(keyPath, 'utf8'),
        cert: fs.readFileSync(certPath, 'utf8'),
      };
    } catch (error) {
      console.error('❌ Error loading development SSL certificates:', error.message);
      throw new Error('Development SSL certificates not found');
    }
  }

  /**
   * Generate self-signed certificate for development
   */
  generateSelfSignedCert(certDir) {
    const WindowsCertGenerator = require('./windows-cert-generator');
    
    try {
      const { keyPath, certPath } = WindowsCertGenerator.generateSelfSignedCert(certDir);
      console.log('✅ Self-signed certificate ready');
      return { keyPath, certPath };
    } catch (error) {
      console.error('❌ Failed to generate self-signed certificate:', error.message);
      throw error;
    }
  }

  /**
   * Create HTTPS server
   */
  createHTTPSServer(app) {
    if (!this.enableHTTPS) {
      console.log('⚠️  HTTPS is disabled. Running in HTTP mode.');
      console.log('💡 Set ENABLE_HTTPS=true in .env to enable HTTPS');
      return http.createServer(app);
    }

    try {
      const credentials = this.getSSLCredentials();
      console.log(`🔒 HTTPS enabled for ${this.environment} environment`);
      return https.createServer(credentials, app);
    } catch (error) {
      console.error('❌ Failed to create HTTPS server:', error.message);
      console.log('⚠️  Falling back to HTTP mode');
      return http.createServer(app);
    }
  }

  /**
   * Setup HTTP to HTTPS redirect
   */
  setupHTTPRedirect(httpsPort = 443) {
    if (!this.enableHTTPS || this.environment !== 'production') {
      return null;
    }

    const redirectApp = http.createServer((req, res) => {
      res.writeHead(301, { Location: `https://${req.headers.host}${req.url}` });
      res.end();
    });

    return redirectApp;
  }
}

module.exports = SSLConfigManager;
